### PR TITLE
Add otel logs to rideshare

### PR DESCRIPTION
**Pull request by simonswine**
In order to show better how the data signals connect I am adding a otel log pusher to our rideshare demo.

Note: The upgrade of otel required an upgrade of dskit, which needed some refactoring in commit f241af5.

Unfortunately the rideshare-app does not log at present, so I had to add a bit of logging as well

https://github.com/grafana/pyroscope/assets/223048/0acb4842-f036-4369-bd8d-3723646c4546

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]
lgtm
Dont understand why updating otel in rideshare requires updates in separate modules? Cant different modules have different dependencies?
Maybe sometime later we should remove rideshare examples from the workspace

**Comment by korniltsev** [comment]
nit: may be it is worth considering cherry-pick dskit upgrade in a separate PR

**Comment by simonswine** [comment]
> Dont understand why updating otel in rideshare requires updates in separate modules? Cant different modules have different dependencies? Maybe sometime later we should remove rideshare examples from the workspace

No idea why it is part of the workspace, maybe the go push library was part of this repo at some point. But the fact it is in the same workspace forces the same grpc version, that then requires dskit upgrades. Once I am back at the keyboard I will split it.

**Comment by simonswine** [comment]
Once I remove it from go.work, it seems to ignore the local go.mod file and can't build it anymore. This is very weird:

```
in the examples/golang-push/rideshare folder
$ go build
main module (github.com/grafana/pyroscope) does not contain package github.com/grafana/pyroscope/examples/golang-push/rideshare

$ go run main.go
main.go:16:2: no required module provides package github.com/agoda-com/opentelemetry-logs-go; to add it:
        go get github.com/agoda-com/opentelemetry-logs-go
main.go:17:2: no required module provides package github.com/pyroscope-io/otel-profiling-go; to add it:
        go get github.com/pyroscope-io/otel-profiling-go
main.go:9:2: package rideshare/bike is not in GOROOT (/nix/store/h2m71h2gy2kr2xvviccxa0mg5jayngcs-go-1.20.8/share/go/src/rideshare/bike)
main.go:10:2: package rideshare/car is not in GOROOT (/nix/store/h2m71h2gy2kr2xvviccxa0mg5jayngcs-go-1.20.8/share/go/src/rideshare/car)
main.go:11:2: package rideshare/rideshare is not in GOROOT (/nix/store/h2m71h2gy2kr2xvviccxa0mg5jayngcs-go-1.20.8/share/go/src/rideshare/rideshare)
main.go:12:2: package rideshare/scooter is not in GOROOT (/nix/store/h2m71h2gy2kr2xvviccxa0mg5jayngcs-go-1.20.8/share/go/src/rideshare/scooter)

```

**Comment by korniltsev** [comment]
maybe GOWORK=off can help building?
```
GOWORK=off go build  -o qwe
```

**Comment by simonswine** [comment]
Yeah that works, unsure if we should keep it in the go.work file then?

**Comment by simonswine** [comment]
Ok I think an "empty" go work file in the examples also does the trick 🙂

**Pull request merged**
