### PR TITLE
chore: renames phlaredb to pyroscopedb

### PR DESCRIPTION
**Pull request by petethepig**
As far as I can tell we don't use this config parameter anywhere. I left some names untouched, because that would break hard, so I think we should change those later e.g:
* https://github.com/pyroscope-io/pyroscope/blob/d97de8a608786a23270b167de18e495f61cfeceb/pkg/storegateway/bucket.go#L45
* https://github.com/pyroscope-io/pyroscope/blob/5dbd4fb1fe294f57651fa70405acf5a666b13d2e/pkg/phlaredb/profile_store.go#L68

### CODE REVIEW

**Comment by simonswine** [comment]
This is should be fine to change https://github.com/pyroscope-io/pyroscope/blob/5dbd4fb1fe294f57651fa70405acf5a666b13d2e/pkg/phlaredb/profile_store.go#L68

**Comment by simonswine** [comment]
Probably while you in the file: https://github.com/grafana/pyroscope/blob/5dbd4fb1fe294f57651fa70405acf5a666b13d2e/pkg/phlaredb/profile_store.go#L69

**Review by Rperry2174 — APPROVED** [review]
lgtm

**Review by simonswine — APPROVED** [review]
LGTM

**Pull request merged**
