### PR TITLE
docs: Add notice about heap profiling

### PR DESCRIPTION
**Pull request by simonswine**
This was a profiler in the dotnet sdk I noticed we are missing.

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]
I am curtain there was a reason we removed live heap from the docs. 
I don't remember and could not find the exact reason though.

**Review by knylander-grafana — APPROVED** [review]
Thank you for updating the docs and the table!

**Comment by knylander-grafana** [comment]
> I am certain there was a reason we removed live heap from the docs. I don't remember and could not find the exact reason though.

Are there any caveats that go along with this option?

**Comment by simonswine** [comment]
> Are there any caveats that go along with this option?

We are not fully sure, at least it requiers .Net 7.0+. Let's document the flag it will be still default off.

**Pull request merged**
