### PR TITLE
fix: usage of `a deprecated Node.js version` in CI

### LINKED ISSUE #3667: `frontend.yml` uses `checkout@v3` and `setup-node@v3` which `use a deprecated Node.js version`
`frontend.yml` uses `actions/checkout@v3` and `actions/setup-node@v3` which `use a deprecated Node.js version`.

### PR DESCRIPTION
**Pull request by hirehamir**
Fixes #3667

### CODE REVIEW

**Review by hirehamir — COMMENTED** [review]
`v4` is the latest major version of `actions/checkout` and `actions/setup-node` at the time of this pull request's creation.

**Comment by marcsanmi** [comment]
Thanks for the contribution @hamirmahal

**Review by marcsanmi — APPROVED** [review]
Thanks for the contribution @hamirmahal

**Comment by hamirmahal** [comment]
You're welcome, @marcsanmi.

**Pull request merged**
