### PR TITLE
[WIP] serviceMonitor support

### PR DESCRIPTION
**Pull request by rlex**
Initial serviceMonitor support

### CODE REVIEW

**Comment by rlex** [comment]
Okay, figured it out. It's working now. Open to suggestions (and unavoidable pipeline fail on initial run)

**Comment by rlex** [comment]
Any suggestions?

**Comment by cyriltovena** [comment]
Looks good to me, what's the problem ?

**Comment by rlex** [comment]
```
/home/runner/work/pyroscope/pyroscope/.tmp/bin/helm template -n default --kube-version "1.22.0" pyroscope-dev ./operations/pyroscope/helm/pyroscope/ \
	| tee ./operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml \
	| /home/runner/work/pyroscope/pyroscope/.tmp/bin/kubeconform --summary --strict --kubernetes-version 1.22.0
```

Hm, i'm not sure what kubeconfirm is, probably should read about it

**Comment by rlex** [comment]
Outdated, it seems, added by different PR

**Pull request closed without merging**
