### PR TITLE
Rename Phlare to Pyroscope in configure client docs

### PR DESCRIPTION
**Pull request by Rperry2174**
Not sure what we need to do to make it show up as pyroscope instead of phlare here:
https://grafana.com/docs/phlare/latest/configure-client/grafana-agent/

### CODE REVIEW

**Comment by simonswine** [comment]
I am unsure what else needs to be updated, but at least the target folder requires updating:

https://github.com/grafana/pyroscope/blob/fa069ab677b904ac8bace9a06ae115d6f8095712/.github/workflows/publish-technical-documentation-release.yml#L80

https://github.com/grafana/pyroscope/blob/fa069ab677b904ac8bace9a06ae115d6f8095712/.github/workflows/publish-technical-documentation-next.yml#L48

@jdbaldry do you mind taking a look at this before we merge. We just don't want to break the website with this update.

**Comment by jdbaldry** [comment]
I didn't see this mention yesterday, I instead opened #2180 because of a conversation I saw in Slack. I think it makes sense to first merge #2180 and then this.

**Comment by Rperry2174** [comment]
> I am unsure what else needs to be updated, but at least the target folder requires updating:
> 
> https://github.com/grafana/pyroscope/blob/fa069ab677b904ac8bace9a06ae115d6f8095712/.github/workflows/publish-technical-documentation-release.yml#L80
> 
> https://github.com/grafana/pyroscope/blob/fa069ab677b904ac8bace9a06ae115d6f8095712/.github/workflows/publish-technical-documentation-next.yml#L48
> 
> @jdbaldry do you mind taking a look at this before we merge. We just don't want to break the website with this update.

@jdbaldry should I do this this PR or should we do it separately?

**Comment by jdbaldry** [comment]
I believe since #2180 is merged, we don't need to update the publishing workflows in this branch.

**Review by bryanhuhta — APPROVED** [review]
:shipit:

**Pull request merged**
