### PR TITLE
Python default in source code is 100

### PR DESCRIPTION
**Pull request by danleyb2**

### CODE REVIEW

**Comment by korniltsev** [comment]
https://github.com/grafana/alloy/blob/12e52a8e5062d2c0b054ec97f6f399ccc1f46ce1/internal/component/pyroscope/ebpf/ebpf_linux.go#L75

**Comment by danleyb2** [comment]
@korniltsev From published PYPI package
https://pypi-browser.org/package/pyroscope-io/pyroscope_io-0.8.7-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/pyroscope/__init__.py#L18

**Comment by korniltsev** [comment]
this PR changes documentation for ebpf profiler 
and the latter link you share is for python pip package profiler
They are not the same

**Comment by danleyb2** [comment]
@korniltsev well, my edit link came from this docs page:
https://grafana.com/docs/pyroscope/latest/configure-client/language-sdks/python/

**Comment by korniltsev** [comment]
This is the link you are looking for https://github.com/grafana/pyroscope/blob/main/docs/sources/configure-client/language-sdks/python.md

**Comment by danleyb2** [comment]
@korniltsev In that case docs are okay

**Pull request closed without merging**
