### PR TITLE
chore(update-contributors): do not skip CI

### PR DESCRIPTION
**Pull request by korniltsev**
[skip ci]  may prevent running goreleaser

### CODE REVIEW

**Comment by marcsanmi** [comment]
Why? AFAIU we only release from specific branches and tags, isn't it?

**Review by marcsanmi — COMMENTED** [review]
Why? AFAIU we only release from specific branches and tags, isn't it?

**Comment by korniltsev** [comment]
image
It happened to me when I created release branch.  It did not run goreleaser-weakly until I touched something in the branch

**Review by marcsanmi — APPROVED** [review]
LGTM. However, just to keep in mind that this change will trigger the CI, including image builds, for every README update.

**Comment by korniltsev** [comment]
> for every README update.
only  weekly / release branches

**Pull request merged**
