### PR TITLE
feat: support resolve symbols in mini debug info(".gnu_debugdata")

### PR DESCRIPTION
**Pull request by zmj64351508**
Mini debug info is stored in a lzma-compressed section named ".gnu_debugdata" in elf. More information can be found in https://archive.fosdem.org/2020/schedule/event/debugging_mini/attachments/slides/4059/export/events/attachments/debugging_mini/slides/4059/fosdem2020_minidebuginfo_kkleine.pdf

When it fails to get symbol in ".symtab", it will try to find the ".gnu_debugdata" section, uncompressing it and read the   data as another elf to get the real "symtab" and "dynsym". (note: even if ".dynsym" exists, ".gnu_debugdata" can store more symbols)

Unfortunately, the original `MMapedElfFile` can't accept an in-memory area as the data of elf file. To reuse the original code to get the symbols, some changes are made:
1. elfmmap.go is split into 2 structs(files):
    a. the origin `struct MMapedElfFile`
    b. the new `struct InMemElfFile`, which is responsible to parse elf for the uncompressed .gnu_debugdata. The original MMapedElfFile also reuse this struct to read elf.
2. A new `interface ElfSymbolReader`, which is used by `struct SymbolTable` to get the symbol string. 
3. A new `struct SymbolTableWithMiniDebugInfo` to combine symbols in original elf and mini debug elf.
4. A new `interface SymbolTableInterface` to abstract SymbolTable and SymbolTableWithMiniDebugInfo.

### CODE REVIEW

**Comment by korniltsev** [comment]
I will take a look into the PR some time later this week.  Please add at least one test extracting symbols from this mini debug info

**Comment by zmj64351508** [comment]
PR Updated, including test

**Comment by korniltsev** [comment]
Thanks. I will be able to take a look next week.

**Review by korniltsev — APPROVED** [review]
thanks

**Pull request merged**
