### PR TITLE
Refactor flamegraph

### PR DESCRIPTION
**Pull request by bryanhuhta**
Also bump github.com/samber/lo

### CODE REVIEW

**Comment by bryanhuhta** [comment]
@simonswine Here's a quick PR that does a small refactor to make fetching node stack pools easier.

**Comment by simonswine** [comment]
@bryanhuhta thanks for your refactoring. I just wonder if it has any performance impact. Let me compare the benchmark for it.

**Comment by bryanhuhta** [comment]
👍 I ran

```
go test ./pkg/model -run ^$ -bench ^BenchmarkFlamegraph$ -benchmem
```

before and after this change and nothing seemed that unusual beyond some noise in the test.

**Comment by simonswine** [comment]
Just verified this locally can't see any impact.

Also uploaded this flamegraph diff: https://flamegraph.com/share/3e81eff2-566f-11ef-ab1b-b6898751f631/3e9383cc-566f-11ef-ab1b-b6898751f631

**Comment by simonswine** [comment]
Ok I have ran this locally, seems to have no impact what so ever:

https://flamegraph.com/share/a5d76bd6-5670-11ef-ab1b-b6898751f631/a5f88d33-5670-11ef-ab1b-b6898751f631

**Comment by simonswine** [comment]
@bryanhuhta I actually found a benchmark tool [pyrobench](https://github.com/grafana/hackathon-2024-08-pyrobench).

That will make this so much easier 🚀

**Comment by simonswine** [comment]
@pyrobench BenchmarkFlamegraph

**Comment by simonswine** [comment]
I think we can do this later

**Pull request closed without merging**
