### PR TITLE
fix: add try catch to request.get to the load-generator of golang-push

### PR DESCRIPTION
**Pull request by richzw**
When the rideshare server starts later than load-generator, the following errors could come up

```
rideshare-load-generator-1  | requesting scooter from ap-south
rideshare-load-generator-1  | Traceback (most recent call last):
rideshare-load-generator-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
rideshare-load-generator-1  |     conn = connection.create_connection(
rideshare-load-generator-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
rideshare-load-generator-1  |     raise err
rideshare-load-generator-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
rideshare-load-generator-1  |     sock.connect(sa)
rideshare-load-generator-1  | ConnectionRefusedError: [Errno 111] Connection refused
rideshare-load-generator-1  |
rideshare-load-generator-1  | During handling of the above exception, another exception occurred:
rideshare-load-generator-1  |
...
rideshare-load-generator-1 exited with code 1
```

As a result, the load-generator could exit. To fix it, add try ... catch block to `requests.get`.

### CODE REVIEW

**Comment by richzw** [comment]
> [CLA assistant check](https://cla-assistant.io/grafana/pyroscope?pullRequest=1933) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/pyroscope?pullRequest=1933) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/pyroscope?pullRequest=1933) it.

The CLA has been signed, but click the recheck, the status is still `not signed yet`

**Comment by Rperry2174** [comment]
Thanks for the help @richzw I know it's tedious but we'd love for all of our load-generators to match. Could you either help us make the same change in:
- [java-jfr](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/java-jfr/rideshare/load-generator.py#L26)
- [fastapi](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/python/rideshare/fastapi/load-generator.py#L24)
- [ruby](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/ruby/rideshare/load-generator.py#L24)
- [nodejs](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/nodejs/load-generator.py#L24)
- [django](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/python/rideshare/django/load-generator.py#L25)

If not happy to do so myself

**Comment by richzw** [comment]
> 

Sure, I will do it.

**Comment by richzw** [comment]
> Thanks for the help @richzw I know it's tedious but we'd love for all of our load-generators to match. Could you either help us make the same change in:
> 
> * [java-jfr](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/java-jfr/rideshare/load-generator.py#L26)
> * [fastapi](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/python/rideshare/fastapi/load-generator.py#L24)
> * [ruby](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/ruby/rideshare/load-generator.py#L24)
> * [nodejs](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/nodejs/load-generator.py#L24)
> * [django](https://github.com/grafana/pyroscope/blob/981d3aa1203ff2e2e07206e7f785adf9382df674/examples/python/rideshare/django/load-generator.py#L25)
> 
> If not happy to do so myself

@Rperry2174 , I have applied this change to all load-generators. Could you please review it again?

**Review by Rperry2174 — APPROVED** [review]
Sorry for the delay here @richzw was out of town for a bit. Thanks so much for the fix!

**Pull request merged**
