### PR TITLE
docs: add home link and sources in Helm chart

### PR DESCRIPTION
**Pull request by froblesmartin**
This is useful to display some links on the artifacthub page: https://artifacthub.io/packages/helm/grafana/pyroscope

For example, you can check the cert-manager one: https://artifacthub.io/packages/helm/cert-manager/cert-manager

image

### CODE REVIEW

**Review by marcsanmi — COMMENTED** [review]
Hi @froblesmartin, thanks for the contribution! 
Could you run `make helm/docs` to update the documentation?

**Comment by froblesmartin** [comment]
> Hi @froblesmartin, thanks for the contribution! Could you run `make helm/docs` to update the documentation?

Done! Thanks for checking! :)

**Comment by marcsanmi** [comment]
I missed that you're using the old home page `https://pyroscope.io/` instead of the new one `https://grafana.com/oss/pyroscope/`. Could you update it please?

**Comment by froblesmartin** [comment]
> I missed that you're using the old home page `https://pyroscope.io/` instead of the new one `https://grafana.com/oss/pyroscope/`. Could you update it please?

Done 👌

**Review by marcsanmi — APPROVED** [review]
LGTM 👍

**Pull request merged**
